name: unit_convert
description: A Dart unit converter to convert between numerous units easily.
version: 0.1.1
homepage: https://github.com/bnxm/unit_convert

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.2.4

dev_dependencies:
  test: ^1.15.7
